apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-server
  namespace: argocd
spec:
  destination:
    name: cloud-a-01
    namespace: petclinic
  project: petclinic
  source:
    path: ./
    repoURL: https://github.com/adamzwickey/spring-petclinic-microservices-config
    targetRevision: tsb-no-code-changes
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true