apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/customers.helm.image-spec: image
    argocd-image-updater.argoproj.io/customers.update-strategy: digest
    argocd-image-updater.argoproj.io/image-list: customers=gcr.io/abz-perm/petclinic-customer-service:v1
    argocd-image-updater.argoproj.io/write-back-method: argocd
  name: customers-service
  namespace: argocd
spec:
  destination:
    name: cloud-a-01
    namespace: petclinic
  project: petclinic
  source:
    helm:
      values: |-
        name: customers-service
        image: gcr.io/abz-perm/petclinic-customer-service@sha256:f406fb5315daa115e196b8d4a79a1dafacab2a45dd511a5aec2fd1ad7da99ca4
        version: v1
        namespace: petclinic
        createNamespace: false
        replicas: 1
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: kubernetes,mysql
          - name: SPRING_CLOUD_DISCOVERY_ENABLED
            value: "false"
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://configserver:8888
          - name: MYSQL_SERVER_FULL_NAME
            value: CHANGEME
          - name: MYSQL_DATABASE_NAME
            value: CHANGEME
          - name: MYSQL_SERVER_ADMIN_LOGIN_NAME
            value: CHANGEME
          - name: MYSQL_SERVER_ADMIN_PASSWORD
            value: CHANGEME
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 1000m
            memory: 1Gi
        ingress:
          create: false
    path: cd/helm/spring-boot
    repoURL: https://github.com/adamzwickey/spring-petclinic-microservices
    targetRevision: tsb-no-code-changes
  syncPolicy:
    automated: {}