name: my-app
image:
  name: gcr.io/abz-perm/my-app
  tag: latest
version: v1
namespace: petclinic
createNamespace: true
replicas: 1
env:
  - name: SPRING_PROFILES_ACTIVE
    value: kubernetes
resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 1Gi
ingress:
  create: true
  name: tsb-petclinic
  domain: petclinic.workshop.cx.tetrate.info
  certificateIssuerName: letsencrypt-dns-cluster-issuer